---
- job: 
    name: vpp-checkstyle
    parent: unittests
    run: test/playbooks/check-style.yaml
    required-projects:
      - lfn-zuul-demo/ci-management

- job: 
    name: vpp-docs
    parent: unittests
    run: test/playbooks/docs.yaml
    required-projects:
      - lfn-zuul-demo/ci-management

- job: 
    name: vpp-make-test-docs
    parent: unittests
    run: test/playbooks/make-test-docs.yaml
    required-projects:
      - lfn-zuul-demo/ci-management

# https://github.com/FDio/ci-management/blob/49b3712b4e2477f38a0e70f1f2d235d51cef1887/jjb/vpp/vpp.yaml#L709
#vpp-verify-master-clang/5065/ (2/8)
#vpp-verify-master-osleap15/6174/ (3/8)
#vpp-verify-master-centos7/16798/ (4/8)
#vpp-verify-master-ubuntu1604/17318/ (5/8)

#vpp-beta-verify-master-ubuntu1804/5141/ (7/8)
#vpp-arm-verify-master-ubuntu1804/933/ (8/8)

- project:
    check:
      jobs:
        - vpp-checkstyle
        - vpp-docs
        - vpp-make-test-docs